<a href="https://colab.research.google.com/github/atulnath/Pytorch-Practice/blob/main/pytorch_day_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## indexing
### selecting data from tensors

In [2]:
import torch
simple_tensor= torch.arange(0,9).reshape(1,3,3)
simple_tensor

tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])

In [3]:
simple_tensor.shape, simple_tensor.ndim

(torch.Size([1, 3, 3]), 3)

In [4]:
simple_tensor[0]

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [5]:
simple_tensor[0][0]

tensor([0, 1, 2])

In [6]:
simple_tensor[0][0][0]

tensor(0)

In [7]:
# Lets print 4

simple_tensor[0][1][1]

tensor(4)

## Pytorch vs Numpy

In [8]:
import numpy as np

np_array = np.arange(0,9)
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
torch_array = torch.from_numpy(np_array) ## Numpy -> Torch
torch_array

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np_array_2 = torch_array.numpy() ## Torch -> Numpy
np_array_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## Random Tensor

In [11]:
A = torch.rand(3,4)
B = torch.rand(3,4)
A

tensor([[0.7963, 0.4171, 0.7667, 0.7972],
        [0.8052, 0.9844, 0.6728, 0.4254],
        [0.1052, 0.7515, 0.6387, 0.2668]])

In [12]:
B

tensor([[0.5081, 0.6115, 0.0013, 0.4175],
        [0.5585, 0.5243, 0.4501, 0.2478],
        [0.7638, 0.0306, 0.2816, 0.5593]])

In [16]:
torch.manual_seed(100) ## Same Random value with seed 100
C = torch.rand(3,4)
C

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])

In [17]:
torch.manual_seed(100) ## Same Random value with seed 100
D = torch.rand(3,4)
D

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])

### CPU VS GPU


In [18]:
torch.cuda.is_available()

False

In [2]:
import torch
torch.cuda.is_available() # After changing the runtime

True

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
torch.cuda.device_count() # Number of GPU

1

In [5]:
A = torch.rand(3,4)
A

tensor([[0.5273, 0.1826, 0.1976, 0.0317],
        [0.0144, 0.1837, 0.1200, 0.6455],
        [0.1182, 0.9505, 0.0296, 0.1795]])

In [6]:
A.device

device(type='cpu')

In [7]:
B = A.to(device)
B

tensor([[0.5273, 0.1826, 0.1976, 0.0317],
        [0.0144, 0.1837, 0.1200, 0.6455],
        [0.1182, 0.9505, 0.0296, 0.1795]], device='cuda:0')

In [8]:
B.device

device(type='cuda', index=0)

In [9]:
B_on_cpu = B.cpu()
B_on_cpu

tensor([[0.5273, 0.1826, 0.1976, 0.0317],
        [0.0144, 0.1837, 0.1200, 0.6455],
        [0.1182, 0.9505, 0.0296, 0.1795]])

In [10]:
B_on_cpu.device

device(type='cpu')