<a href="https://colab.research.google.com/github/atulnath/Pytorch-Practice/blob/main/pytorch_Day_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Datatype

In [2]:
import torch
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.7132, 0.7525, 0.8527, 0.4449],
        [0.4205, 0.4463, 0.4411, 0.1066],
        [0.6355, 0.6851, 0.5673, 0.6306]])

In [3]:
rand_tensor.dtype

torch.float32

In [4]:
another_rand_tensor = torch.tensor([1,2,3,4])
another_rand_tensor

tensor([1, 2, 3, 4])

In [5]:
## Using arrange

arrange_torch=torch.arange(start=0.,end=10.,step=2)
arrange_torch

tensor([0., 2., 4., 6., 8.])

In [6]:
arrange_torch.dtype

torch.float32

In [7]:
sample_torch=torch.zeros_like(input=arrange_torch,dtype=int)
sample_torch

tensor([0, 0, 0, 0, 0])

In [8]:
## Changing datatype
new_type=arrange_torch.type(torch.float16)
new_type

tensor([0., 2., 4., 6., 8.], dtype=torch.float16)

## Information about tensor



*   shape
*   dtype
*   device





In [9]:
one_tensor=torch.ones(size=(2,3,4))
one_tensor

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
one_tensor.shape, one_tensor.dtype,one_tensor.device

(torch.Size([2, 3, 4]), torch.float32, device(type='cpu'))

## Operations

In [12]:
# Addition
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [13]:
tensor_2=torch.tensor([10,20,30])
tensor+tensor_2

tensor([11, 22, 33])

In [14]:
torch.add(tensor,tensor_2) # Same thing

tensor([11, 22, 33])

In [15]:
# subtraction

tensor-10

tensor([-9, -8, -7])

In [16]:
torch.subtract(tensor,tensor_2) # Same thing

tensor([ -9, -18, -27])

In [17]:
# Multiplication
torch.multiply(tensor,tensor_2), torch.mul(tensor,tensor_2) # Same thing


(tensor([10, 40, 90]), tensor([10, 40, 90]))

In [18]:
# Division
torch.divide(tensor,tensor_2), torch.div(tensor,tensor_2) # Same thing

(tensor([0.1000, 0.1000, 0.1000]), tensor([0.1000, 0.1000, 0.1000]))

In [19]:
# Matrix multiplication

matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
matrx_2=torch.tensor([[5,6,7],[8,9,1]])
matrx_2

tensor([[5, 6, 7],
        [8, 9, 1]])

In [22]:
torch.mul(matrix,matrx_2)

tensor([[ 5, 12, 21],
        [32, 45,  6]])

In [23]:
torch.multiply(matrix,matrx_2)

tensor([[ 5, 12, 21],
        [32, 45,  6]])

In [24]:
matrix.shape, matrx_2.shape

(torch.Size([2, 3]), torch.Size([2, 3]))