<a href="https://colab.research.google.com/github/atulnath/Pytorch-Practice/blob/main/pytorch_05_07_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# y = x^2 + 3x + 1

x_value=torch.tensor(2.0,requires_grad=True)
y_value=x_value**2+3*x_value+1
y_value.backward() # Count Gradient
x_value.grad # dy/dx = 2x + 3, putting x = 2, dy/dx = 7

tensor(7.)

In [3]:
# multiple tensor and gradient

a=torch.tensor(2.0,requires_grad=True)
b=torch.tensor(3.0,requires_grad=True)

z = a*b + b**2 # z = ab + b^2
z.backward()
print(a.grad) # dz/da = b = 3
print(b.grad) # dz/db = a + 2 b = 2 + 2 * 3 = 8

tensor(3.)
tensor(8.)


In [5]:
# Let take a data

X = torch.tensor([[1],[2],[3]],dtype=torch.float32, requires_grad=False)
X

tensor([[1.],
        [2.],
        [3.]])

In [6]:
# Target Data, Y = 2X
Y_Actual = torch.tensor([[2],[4],[6]],dtype=torch.float32)
Y_Actual

tensor([[2.],
        [4.],
        [6.]])

In [7]:
# Let define a weight function
weight = torch.tensor([[1]],dtype=torch.float32,requires_grad=True)
weight

tensor([[1.]], requires_grad=True)

In [8]:
# Bias should be 0 as because of y = 2X
bias = torch.tensor([[0]],dtype=torch.float32,requires_grad=True)
bias

tensor([[0.]], requires_grad=True)

In [10]:
# Prediction which we will compare with with Y_Actual
Y_Predicted = X @ weight + bias # Linear Regression equation
Y_Predicted

tensor([[1.],
        [2.],
        [3.]], grad_fn=<AddBackward0>)

In [11]:
loss = torch.mean((Y_Predicted - Y_Actual)**2)
loss

tensor(4.6667, grad_fn=<MeanBackward0>)

In [12]:
loss.backward()

In [13]:
weight.grad

tensor([[-9.3333]])

In [14]:
bias.grad

tensor([[-4.]])