<a href="https://colab.research.google.com/github/atulnath/Pytorch-Practice/blob/main/pyTorch_Revision_06_06_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
#scalar
x = torch.empty(1) # Here 1 is the size
x

tensor([1.0801e-30])

In [5]:
#vector
x = torch.empty(3)
x

tensor([0.0000, 0.0000, 0.5951])

In [6]:
#matrix
x = torch.empty(3,2)
x

tensor([[5.9513e-01, 0.0000e+00],
        [5.9512e-01, 0.0000e+00],
        [1.1210e-43, 0.0000e+00]])

In [7]:
#tensor, 3 dimensions
x = torch.empty(3,2,3)
x

tensor([[[8.6051e-02, 0.0000e+00, 1.0465e-30],
         [4.3980e-41, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 1.4013e-45, 0.0000e+00]]])

In [8]:
#Random
x = torch.rand(2,2)
x

tensor([[0.3723, 0.1097],
        [0.7361, 0.0111]])

In [9]:
x = torch.zeros(2,2)
y = torch.ones(2,2)
print("zeros(2,2)\n",x)
print("torch.ones(2,2)\n",y)

zeros(2,2)
 tensor([[0., 0.],
        [0., 0.]])
torch.ones(2,2)
 tensor([[1., 1.],
        [1., 1.]])


In [10]:
#checking size

x = torch.rand(3,2)
print(x.size()) #Function
print(x.shape) #Atribute

print(x.size(0)) #Function
print(x.shape[1]) #Atribute
print(x.dtype)

torch.Size([3, 2])
torch.Size([3, 2])
3
2
torch.float32


In [11]:
x = torch.ones(2,2, dtype=torch.int)
print(x.dtype)

torch.int32


In [12]:
#Tensor from list or numpy data

x = torch.tensor([2.5, 0.1])
print(x)
print(x.dtype)

tensor([2.5000, 0.1000])
torch.float32


In [13]:
#For optimization we use requires_grad argument to calculate the gradients

x = torch.tensor([2.5, 0.1], requires_grad=True)
print(x)
print(x.dtype)

tensor([2.5000, 0.1000], requires_grad=True)
torch.float32


In [14]:
#numpy operations

x = torch.ones(2,3)
y = torch.rand(2,3)
print(x)
print(y)

res = x + y # torch.add(x,y)
print(res)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.6960, 0.9951, 0.5249],
        [0.2724, 0.4907, 0.0187]])
tensor([[1.6960, 1.9951, 1.5249],
        [1.2724, 1.4907, 1.0187]])


In [15]:
#subtraction

res = x - y
print(res)

#multiplication

res = x * y
print(res)

#division

res = x / y
print(res)



tensor([[0.3040, 0.0049, 0.4751],
        [0.7276, 0.5093, 0.9813]])
tensor([[0.6960, 0.9951, 0.5249],
        [0.2724, 0.4907, 0.0187]])
tensor([[ 1.4367,  1.0049,  1.9052],
        [ 3.6714,  2.0380, 53.4490]])


In [16]:
#slicing

x = torch.rand(4,2)

print(x)

# all row of col 0

print(x[:,0])

# row 1, all col

print(x[1,:])

#to access single element

print(x[0,1])

tensor([[0.2203, 0.1604],
        [0.1382, 0.5262],
        [0.8669, 0.6359],
        [0.6913, 0.2428]])
tensor([0.2203, 0.1382, 0.8669, 0.6913])
tensor([0.1382, 0.5262])
tensor(0.1604)


In [17]:
# to get complete float value item()

print(x[0,1].item())

0.1603986620903015


In [18]:
#Reshaping with tensor.view()

x = torch.rand(3,4) #3 rows, 4 cols
print(x)

y = x.view(12)
print(y)

z = x.view(-1,6)
print(z)

x.size(), y.size(), z.size()

tensor([[0.9971, 0.1576, 0.6660, 0.0170],
        [0.6833, 0.1273, 0.6525, 0.9468],
        [0.2410, 0.8415, 0.6219, 0.2127]])
tensor([0.9971, 0.1576, 0.6660, 0.0170, 0.6833, 0.1273, 0.6525, 0.9468, 0.2410,
        0.8415, 0.6219, 0.2127])
tensor([[0.9971, 0.1576, 0.6660, 0.0170, 0.6833, 0.1273],
        [0.6525, 0.9468, 0.2410, 0.8415, 0.6219, 0.2127]])


(torch.Size([3, 4]), torch.Size([12]), torch.Size([2, 6]))

In [19]:
#Tensor to numpy

a = torch.ones(3)

print(a)

b = a.numpy()

print(b)

print(type(b))

tensor([1., 1., 1.])
[1. 1. 1.]
<class 'numpy.ndarray'>


In [20]:
#CPU change value of a will change the value of b as they share same
#memory locations

a.add_(2)
print(a)
print(b)

tensor([3., 3., 3.])
[3. 3. 3.]
