<a href="https://colab.research.google.com/github/atulnath/Pytorch-Practice/blob/main/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing pytorch

import torch
import torch.nn as nn

In [2]:
# Lets create tensor with 2 x 3 matrix

x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [3]:
x.shape # it shows dimensions of tensors

torch.Size([2, 3])

In [4]:
# Lets create a random tensor

random_tens = torch.rand(2,3)
random_tens # values are betwee 0 and 1

tensor([[0.7364, 0.7217, 0.4377],
        [0.6631, 0.2163, 0.3532]])

In [5]:
# Tensor common operations: +, -, *, /

sum_tens = x + random_tens
sum_tens

tensor([[1.7364, 2.7217, 3.4377],
        [4.6631, 5.2163, 6.3532]])

In [8]:
# For making gradient tensor
ones_tens = torch.ones(2,3, requires_grad=True)
ones_tens

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [9]:
# y = x ** 2 means square of x

y = x ** 2
y

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [10]:
grad_tens = ones_tens ** 2
grad_tens

tensor([[1., 1., 1.],
        [1., 1., 1.]], grad_fn=<PowBackward0>)

In [11]:
grad_tens.backward(torch.ones_like(grad_tens))

In [12]:
ones_tens.grad

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [13]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(2, 4) # 2 input and 4 output (full connected layer fc1)
        self.fc2 = nn.Linear(4, 1) # 4 input, 1 ouput (full connected layer fc2)

    def forward(self, x):
        x = torch.relu(self.fc1(x)) # relu activation function
        x = self.fc2(x)
        return x
model = Net()
print(model)

Net(
  (fc1): Linear(in_features=2, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=1, bias=True)
)


In [14]:
# Loss function

loss = nn.MSELoss()
optimization = torch.optim.SGD(model.parameters(), lr=0.01)

# Here MSE loss function, SGD optimizer and lr is learning rate

In [16]:
x_train = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
y_train = torch.tensor([[3], [7], [11]], dtype=torch.float32)

In [17]:
for epoach in range(100):
  optimization.zero_grad()
  output = model(x_train)
  loss_value = loss(output, y_train)
  loss_value.backward()
  optimization.step()

print(model(x_train))

tensor([[ 3.1219],
        [ 7.0333],
        [10.9447]], grad_fn=<AddmmBackward0>)


In [18]:
output = model(x_train)
print(output)

tensor([[ 3.1219],
        [ 7.0333],
        [10.9447]], grad_fn=<AddmmBackward0>)


In [19]:
print(f' Final loss: {loss_value.item()}')

 Final loss: 0.006490430328994989


In [21]:
x_test= torch.tensor([[2,3]], dtype=torch.float32)
print(model(x_test))

tensor([[5.0776]], grad_fn=<AddmmBackward0>)


In [23]:
test_output = model(x_test)
print(test_output)

tensor([[5.0776]], grad_fn=<AddmmBackward0>)


In [24]:
print(f'Test Predic: {test_output.item()}')

Test Predic: 5.07763671875
