<a href="https://colab.research.google.com/github/atulnath/Pytorch-Practice/blob/main/pytorch_practice_30_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch


print(torch.__version__)

#Zero dimension tensor(Scaler)
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)

#For one element tensor we can use item() to get item

print(scalar.item())

2.6.0+cu124
tensor(7)
0
7


#Vector

one dimension tensor with multiple values in it

In [10]:
vector = torch.tensor([7,8])
print(vector)
print(vector.ndim)

tensor([7, 8])
<built-in method size of Tensor object at 0x7c2b31dd0f50>
1


#Matrix

In [12]:
mat = torch.tensor([[7,8],[9,10]])
print(mat)
print(mat.ndim)

tensor([[ 7,  8],
        [ 9, 10]])
2


#tensor
multiple dimensions

In [14]:
ten = torch.tensor([[[7,8],[9,10]],[[1,2],[3,4]]])
print(ten)
print(ten.ndim)
print("Shape: ",ten.shape)

tensor([[[ 7,  8],
         [ 9, 10]],

        [[ 1,  2],
         [ 3,  4]]])
3
Shape:  torch.Size([2, 2, 2])


#Random number

In [15]:
random_tensor=torch.rand(size=(3,4))
random_tensor,random_tensor.dtype

(tensor([[0.1547, 0.1326, 0.4160, 0.7314],
         [0.4911, 0.3141, 0.8308, 0.5727],
         [0.5285, 0.8352, 0.6165, 0.5295]]),
 torch.float32)

In [16]:
#Image using random tensor

random_image = torch.rand(size=(224,244,3))
print(random_image, random_image.shape)

tensor([[[0.6189, 0.0380, 0.1408],
         [0.3393, 0.0844, 0.5423],
         [0.3408, 0.7401, 0.9581],
         ...,
         [0.8927, 0.9117, 0.9753],
         [0.7993, 0.9257, 0.0401],
         [0.9260, 0.6908, 0.6476]],

        [[0.5559, 0.2879, 0.6161],
         [0.5658, 0.1126, 0.1854],
         [0.7643, 0.9114, 0.0980],
         ...,
         [0.6445, 0.2988, 0.9644],
         [0.1532, 0.0868, 0.0861],
         [0.4758, 0.6408, 0.8978]],

        [[0.8210, 0.7040, 0.0314],
         [0.9347, 0.7969, 0.6745],
         [0.3792, 0.1846, 0.9543],
         ...,
         [0.4269, 0.5362, 0.6795],
         [0.1647, 0.5001, 0.0460],
         [0.8734, 0.8787, 0.4380]],

        ...,

        [[0.2809, 0.9928, 0.1058],
         [0.2179, 0.0798, 0.4629],
         [0.1341, 0.9078, 0.8416],
         ...,
         [0.4337, 0.0214, 0.9417],
         [0.2957, 0.9022, 0.0631],
         [0.7568, 0.6557, 0.8322]],

        [[0.2529, 0.4449, 0.2095],
         [0.6768, 0.9659, 0.1301],
         [0.

#Zeros and Ones tensors

In [20]:
zeros= torch.zeros(size=(3,4))
ones= torch.ones(size=(3,4))
zeros, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

#Range in tensor

In [22]:
nums= torch.arange(10)
zeros_tens_like_nums= torch.zeros_like(input=nums)

nums,zeros_tens_like_nums

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

#Info about a tensor
shape, dtype, device(GPU,CPU)

In [24]:
rand_tensor= torch.rand(size=(3,4))
rand_tensor, rand_tensor.dtype, rand_tensor.device

(tensor([[0.9843, 0.9836, 0.4472, 0.3434],
         [0.5967, 0.6735, 0.0152, 0.3689],
         [0.0065, 0.4484, 0.8093, 0.8366]]),
 torch.float32,
 device(type='cpu'))

#Tensor Manipulations

In [25]:
tens= torch.tensor([2,3,4])
tens + 10, tens - 1, tens * 2

(tensor([12, 13, 14]), tensor([1, 2, 3]), tensor([4, 6, 8]))

In [26]:
#Replacing the value

tens = tens + 9
tens

tensor([11, 12, 13])

# Multiply builtin function

In [28]:
tens_01 = torch.multiply(tens, 3)
print(tens_01)

tensor([33, 36, 39])


#multiply between two tensors

In [29]:
tens1 = torch.tensor([2,3,5])
tens2 = torch.tensor([4,7,8])

tens1 * tens2

tensor([ 8, 21, 40])