<a href="https://colab.research.google.com/github/atulnath/Pytorch-Practice/blob/main/pytorch_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



*   max
*   min
*   mean
*   sum





In [1]:
import torch

In [2]:
x = torch.arange(1,5)
x

tensor([1, 2, 3, 4])

In [3]:
x.min(), x.max()

(tensor(1), tensor(4))

In [4]:
x.sum()

tensor(10)

In [6]:
x = torch.tensor(x, dtype=torch.float32)
x

/tmp/ipython-input-6-1756322803.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32)


tensor([1., 2., 3., 4.])

In [7]:
x.mean()

tensor(2.5000)

In [8]:
# Return index of min and max

x.argmin(), x.argmax()

(tensor(0), tensor(3))



1.   Reshaping
2.   stacking
3.   Squezing
4.   Unsquezing
5.   Permute



In [9]:
# Reshape

x = torch.arange(1.,10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
x_reshape= x.reshape(3,3)
x_reshape

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [11]:
# Reshape vs View

z = x.view(3,3)
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [12]:
z[0,0] = 47
z

tensor([[47.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]])

In [13]:
x # Changes happens to x also if we change on view

tensor([47.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [14]:

x = torch.arange(1.,10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [15]:
# stack: all the tensor size should be same

x_stack = torch.stack([x,x,x], dim=0) # dim= 0, row-wise
x_stack

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [16]:
x_stack = torch.stack([x,x,x], dim=1) # dim= 0, col-wise
x_stack

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [17]:
x = torch.arange(1.,10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [18]:
# unsqueeze

x_unsqueeze = x.unsqueeze(dim=0) # add one more dimension
x_unsqueeze

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [19]:
x_unsqueeze = x.unsqueeze(dim=0)# add one more dimension
x_unsqueeze

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [20]:
x_unsqueeze = x.unsqueeze(dim=1) # add one more dimension
x_unsqueeze

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [22]:
x_unsqueeze =x_unsqueeze.unsqueeze(dim=1) # add one more dimension
x_unsqueeze

tensor([[[1.]],

        [[2.]],

        [[3.]],

        [[4.]],

        [[5.]],

        [[6.]],

        [[7.]],

        [[8.]],

        [[9.]]])

In [23]:
x_squeeze =  x_unsqueeze.squeeze()
x_squeeze

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
# Permute

x = torch.rand(size=(224,224,3))
x

tensor([[[0.5607, 0.1314, 0.5439],
         [0.3940, 0.2953, 0.9098],
         [0.8031, 0.7962, 0.5043],
         ...,
         [0.5459, 0.5508, 0.5685],
         [0.3297, 0.8767, 0.7675],
         [0.4962, 0.2779, 0.6384]],

        [[0.6552, 0.3949, 0.3421],
         [0.7022, 0.1774, 0.5074],
         [0.1846, 0.5464, 0.2521],
         ...,
         [0.6567, 0.4554, 0.3483],
         [0.2200, 0.9936, 0.9676],
         [0.7682, 0.3161, 0.5723]],

        [[0.4508, 0.1206, 0.3233],
         [0.7570, 0.7128, 0.3206],
         [0.0444, 0.7191, 0.7397],
         ...,
         [0.9128, 0.8645, 0.7053],
         [0.1577, 0.6268, 0.2261],
         [0.9695, 0.9467, 0.9578]],

        ...,

        [[0.7670, 0.2323, 0.0304],
         [0.9596, 0.6083, 0.8346],
         [0.4080, 0.4776, 0.5553],
         ...,
         [0.5668, 0.4480, 0.6383],
         [0.6038, 0.5433, 0.7157],
         [0.9929, 0.8109, 0.2715]],

        [[0.6924, 0.9599, 0.2566],
         [0.2682, 0.1032, 0.5291],
         [0.

In [25]:
x_permute = x.permute(2,0,1) # 2, 0, 1 are index, now it changed the our original shape
x_permute # [new shape] => 3 224 224

tensor([[[0.5607, 0.3940, 0.8031,  ..., 0.5459, 0.3297, 0.4962],
         [0.6552, 0.7022, 0.1846,  ..., 0.6567, 0.2200, 0.7682],
         [0.4508, 0.7570, 0.0444,  ..., 0.9128, 0.1577, 0.9695],
         ...,
         [0.7670, 0.9596, 0.4080,  ..., 0.5668, 0.6038, 0.9929],
         [0.6924, 0.2682, 0.2312,  ..., 0.4283, 0.6672, 0.9404],
         [0.7095, 0.5082, 0.3751,  ..., 0.1032, 0.8931, 0.8087]],

        [[0.1314, 0.2953, 0.7962,  ..., 0.5508, 0.8767, 0.2779],
         [0.3949, 0.1774, 0.5464,  ..., 0.4554, 0.9936, 0.3161],
         [0.1206, 0.7128, 0.7191,  ..., 0.8645, 0.6268, 0.9467],
         ...,
         [0.2323, 0.6083, 0.4776,  ..., 0.4480, 0.5433, 0.8109],
         [0.9599, 0.1032, 0.3365,  ..., 0.1641, 0.6135, 0.9264],
         [0.4657, 0.1683, 0.4099,  ..., 0.7902, 0.3731, 0.3202]],

        [[0.5439, 0.9098, 0.5043,  ..., 0.5685, 0.7675, 0.6384],
         [0.3421, 0.5074, 0.2521,  ..., 0.3483, 0.9676, 0.5723],
         [0.3233, 0.3206, 0.7397,  ..., 0.7053, 0.2261, 0.

In [26]:
x_permute.shape

torch.Size([3, 224, 224])