<a href="https://colab.research.google.com/github/atulnath/Pytorch-Practice/blob/main/pytorch_06_07_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.randn(5, requires_grad=True)
x

tensor([-0.7360,  1.1071,  0.1660,  0.0087, -0.6589], requires_grad=True)

In [3]:
y = x + 2
y

tensor([1.2640, 3.1071, 2.1660, 2.0087, 1.3411], grad_fn=<AddBackward0>)

In [4]:
z = y * y * 2

In [5]:
z

tensor([ 3.1953, 19.3087,  9.3830,  8.0696,  3.5973], grad_fn=<MulBackward0>)

In [10]:
z = z.mean()

In [11]:
z

tensor(8.7108, grad_fn=<MeanBackward0>)

In [12]:
z.backward()

In [13]:
x.grad

tensor([1.0112, 2.4857, 1.7328, 1.6069, 1.0729])