<a href="https://colab.research.google.com/github/atulnath/Pytorch-Practice/blob/main/pytorch%20day02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Random tensors

In [1]:
import torch

In [2]:
rand_tensor=torch.rand(3,4)
rand_tensor

tensor([[0.7297, 0.0701, 0.3420, 0.5735],
        [0.1869, 0.9853, 0.0300, 0.1019],
        [0.9615, 0.8174, 0.4782, 0.2355]])

In [3]:
big_rand_tensor=torch.rand((1,3,4))
big_rand_tensor

tensor([[[0.2448, 0.0256, 0.2323, 0.2268],
         [0.6808, 0.3113, 0.8516, 0.4659],
         [0.6143, 0.6527, 0.7935, 0.2892]]])

## Zeros and ones

In [4]:
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
zeros = torch.ones((1,3,4))
zeros

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

## arrange

In [6]:
list_of_numbers=torch.arange(start=0,end=10,step=1)
list_of_numbers

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## tensor like

In [7]:
rand_tens = torch.rand(3,4)
rand_tens

tensor([[0.0564, 0.3980, 0.5512, 0.5426],
        [0.0932, 0.1503, 0.7920, 0.0778],
        [0.3012, 0.2004, 0.0926, 0.2109]])

In [8]:
zeros_like=torch.zeros_like(rand_tens)
zeros_like

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
one_like = torch.ones_like(rand_tens)
one_like

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Eye

In [10]:
eye_tensor = torch.eye(5)
eye_tensor

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
# Full tensor
full_tensor = torch.full((2,3),5)
full_tensor

tensor([[5, 5, 5],
        [5, 5, 5]])

In [12]:
# linspace
linspace_tensor = torch.linspace(0,10,5) # go 0 to 10, divide into 5 times
linspace_tensor

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])