<a href="https://colab.research.google.com/github/atulnath/Pytorch-Practice/blob/main/torch_learning_28_06_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

torch.__version__

'2.6.0+cu124'

In [2]:
# Scalar is zero dimension tensor, a single number

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.shape

torch.Size([])

In [4]:
scalar.ndim # checking the dimensions

0

In [5]:
# accessing item in scalar tensor
scalar.item()

7

In [6]:
# vector is 1D tensor, like list 1D list in python

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape # shape return how many items in the vector

torch.Size([2])

In [9]:
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
tensor = torch.tensor([[[1,2,3,4],
                        [4,5,6,4],
                        [7,8,9,8]]])
tensor

tensor([[[1, 2, 3, 4],
         [4, 5, 6, 4],
         [7, 8, 9, 8]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 4])

In [15]:
## Random Tensors

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8798, 0.1437, 0.4816, 0.7422],
        [0.6398, 0.7159, 0.3557, 0.5694],
        [0.3380, 0.6442, 0.4457, 0.7674]])

In [16]:
random_tensor.ndim

2

In [17]:
random_tensor.shape

torch.Size([3, 4])

In [18]:
big_tensor= torch.rand(224, 224, 3)
big_tensor

tensor([[[0.4453, 0.8991, 0.9956],
         [0.3857, 0.4114, 0.0841],
         [0.6251, 0.5880, 0.4276],
         ...,
         [0.8703, 0.0923, 0.6952],
         [0.3818, 0.6178, 0.5069],
         [0.5743, 0.5349, 0.4667]],

        [[0.2913, 0.5284, 0.9812],
         [0.3041, 0.5026, 0.1840],
         [0.2628, 0.4994, 0.6703],
         ...,
         [0.3514, 0.3031, 0.4821],
         [0.3840, 0.4716, 0.2848],
         [0.5895, 0.6543, 0.1681]],

        [[0.6460, 0.2293, 0.8925],
         [0.6496, 0.0121, 0.2246],
         [0.8554, 0.7680, 0.0812],
         ...,
         [0.0917, 0.3379, 0.0631],
         [0.2704, 0.5867, 0.2841],
         [0.0167, 0.7277, 0.2589]],

        ...,

        [[0.8203, 0.7563, 0.6296],
         [0.7462, 0.3365, 0.6223],
         [0.8419, 0.5984, 0.0992],
         ...,
         [0.0342, 0.5084, 0.7374],
         [0.1560, 0.0566, 0.1185],
         [0.9005, 0.2227, 0.7703]],

        [[0.3437, 0.5675, 0.1908],
         [0.8427, 0.6050, 0.1425],
         [0.

In [19]:
big_tensor.ndim

3

In [20]:
big_tensor.shape

torch.Size([224, 224, 3])

In [21]:
# For masking we need to use
# Zeros and Ones tensor

zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones=torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])